name: lmm_user
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  http: ^1.2.2
  http_parser: ^4.0.0
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  shared_preferences:
  pin_code_fields: ^8.0.1
  flutter_styled_toast: ^2.2.1
  intl: ^0.19.0
  get: ^4.3.8
  intl_phone_field: ^3.1.0
  fluttertoast: ^8.0.9
  flutter_spinkit: ^5.1.0
  page_transition: ^2.0.4
  flutter_local_notifications: any
  country_code_picker: ^3.0.0
  device_info_plus: ^9.0.3
  event_manager: ^0.0.7
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  camera: ^0.10.5+4
  #==============================
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.1.1
  place_picker_google: ^0.0.15
  google_places_flutter: ^2.0.0
  flutter_polyline_points: ^2.1.0
  flutter_inappwebview: ^6.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
